name: RSS to Telegram

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

jobs:
  rss_to_telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    #- name: Ensure cache directory and file
      #run: |
        #mkdir -p $GITHUB_WORKSPACE/cache
        #if [ ! -f "$GITHUB_WORKSPACE/cache/feed_cache.json" ]; then
       #   echo '{}' > "$GITHUB_WORKSPACE/cache/feed_cache.json"
        #fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the RSS to Telegram script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        python send_rss_to_telegram.py
